load("cs_test", "cs_test")

cs_test(
  name = "class",
  src = "class.cc",
)

cs_test(
  name = "directory_navigation",
  src = "directory_navigation.cc",
)

cs_test(
  name = "enum",
  src = "enum.cc",
)

cs_test(
  name = "field",
  src = "field.cc",
)

cs_test(
  name = "function",
  src = "function.cc",
)

cs_test(
  name = "multiple_definitions",
  src = "multiple_definitions.cc",
)

cs_test(
  name = "search",
  src = "search.cc",
)

cs_test(
  name = "template_outline",
  src = "template_outline.cc",
)

cs_test(
  name = "variable",
  src = "variable.cc",
)
