package(default_visibility = ["//visibility:public"])

load("//tools:build_rules/go.bzl", "go_package_library")

licenses(["notice"])

go_package_library(
    name = "defindex",
    srcs = ["defindex.go"],
)
