package(default_visibility = ["//visibility:public"])

load("/third_party/go/build", "gopath_package")

licenses(["notice"])

gopath_package(
    deps = [
        "//kythe/cs/cshtml",
        "//kythe/cs/defindex",
        "//kythe/cs/refpack",
        "//third_party/go/src/github.com/google/codesearch/index",
        "//third_party/go/src/github.com/google/codesearch/regexp",
    ],
)
